# Generated by Django 3.2.8 on 2021-10-23 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=255, verbose_name='account name')),
                ('account_number', models.CharField(max_length=20, verbose_name='account number')),
                ('bank_code', models.CharField(max_length=5, verbose_name='bank code')),
                ('bank_name', models.CharField(max_length=255, verbose_name='bank name')),
                ('transfer_recipient', models.CharField(max_length=255, verbose_name='transfer_recipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
