# Generated by Django 3.2.8 on 2021-10-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_bank_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(max_length=10, verbose_name='bank code'),
        ),
    ]
