# Generated by Django 3.2.8 on 2021-10-23 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_alter_bank_bank_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorization_code', models.CharField(max_length=255, verbose_name='authorization code')),
                ('card_type', models.CharField(max_length=128, verbose_name='card type')),
                ('last4', models.CharField(max_length=4, verbose_name='last 4 digits')),
                ('exp_month', models.CharField(max_length=2, verbose_name='expiry month')),
                ('exp_year', models.CharField(max_length=4, verbose_name='expiry year')),
                ('bin', models.CharField(max_length=6, verbose_name='bin')),
                ('bank', models.CharField(max_length=255, verbose_name='bank')),
                ('channel', models.CharField(max_length=128, verbose_name='channel')),
                ('signature', models.CharField(max_length=255, verbose_name='signature')),
                ('reusable', models.BooleanField(verbose_name='reusuable card')),
                ('country_code', models.CharField(max_length=5, verbose_name='country code')),
                ('account_name', models.CharField(blank=True, max_length=255, verbose_name='account name')),
                ('is_default', models.BooleanField(default=False, verbose_name='default bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
