# Generated by Django 3.2.8 on 2021-10-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='account_name',
        ),
    ]
