# Generated by Django 3.2.8 on 2021-10-27 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_alter_cycle_end_date'),
        ('transactions', '0006_card_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(verbose_name='order')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lists', to='groups.cycle')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lists', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
