# Generated by Django 3.2.8 on 2021-10-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20211027_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlist',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_list', to='transactions.transaction'),
        ),
    ]
