# Generated by Django 3.2.8 on 2021-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20211022_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
    ]
